table:
  name: settings
  schema: public
select_permissions:
  - role: guest
    permission:
      columns:
        - masks_category
      filter: {}
  - role: user
    permission:
      columns:
        - id
        - masks_category
      filter: {}
