version: 3
endpoint: http://localhost:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
# https://hasura.tvoyapolychka.com.ua
# http://localhost:8080