name: Deploy Hasura

on: workflow_dispatch

jobs:
  deploy-hasura:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        uses: borales/actions-npm@v3.0.0

      - name: Deploy
        run: |
          npx hasura metadata apply --endpoint https://hasura.tvoyapolychka.com.ua/ --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }}
          npx hasura migrate apply --endpoint https://hasura.tvoyapolychka.com.ua/ --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }} --database-name default
